package packet

import (
	"reflect"
)

func t(v interface{}) reflect.Type {
	return reflect.TypeOf(v)
}

var HandshakeClientboundIds = map[int32]reflect.Type{
}

var HandshakeServerboundIds = map[int32]reflect.Type{
	0x00: t(ServerboundHandshakePacket{}),
	0xFE: t(ServerboundHandshakeLegacyPingPacket{}),
}

var StatusClientboundIds = map[int32]reflect.Type{
	0x00: t(ClientboundStatusResponsePacket{}),
	0x01: t(ClientboundStatusPongPacket{}),
}

var StatusServerboundIds = map[int32]reflect.Type{
	0x00: t(ServerboundStatusRequestPacket{}),
	0x01: t(ServerboundStatusPingPacket{}),
}

var LoginClientboundIds = map[int32]reflect.Type{
	0x00: t(ClientboundLoginDisconnectPacket{}),
	0x01: t(ClientboundLoginEncryptionRequest{}),
	0x02: t(ClientboundLoginSuccess{}),
	0x03: t(ClientboundLoginCompressionPacket{}),
	0x04: t(ClientboundLoginPluginRequest{}),
}

var LoginServerboundIds = map[int32]reflect.Type{
	0x00: t(ServerboundLoginStartPacket{}),
	0x01: t(ServerboundLoginEncryptionResponsePacket{}),
	0x02: t(ServerboundLoginPluginResponsePacket{}),
}

var PlayClientboundIds = map[int32]reflect.Type{
	0x00: t(ClientboundSpawnEntityPacket{}),
	0x01: t(ClientboundSpawnEntityExperienceOrbPacket{}),
	0x02: t(ClientboundSpawnEntityLivingPacket{}),
	0x03: t(ClientboundSpawnEntityPaintingPacket{}),
	0x04: t(ClientboundPlaySpawnPlayerPacket{}),
	0x05: t(ClientboundPlayEntityAnimationPacket{}),
	0x06: t(ClientboundPlayStatisticsPacket{}),
	0x07: t(ClientboundPlayAcknowledgePlayerDiggingPacket{}),
	0x08: t(ClientboundPlayBlockBreakAnimationPacket{}),
	0x09: t(ClientboundPlayBlockEntityDataPacket{}),
	0x0A: t(ClientboundPlayBlockActionPacket{}),
	0x0B: t(ClientboundPlayBlockChange{}),
	0x0C: t(ClientboundPlayBossBar{}),
	0x0D: t(ClientboundServerDifficultyPacket{}),
	0x0E: t(ClientboundPlayChat{}),
	0x0F: t(ClientboundPlayTabComplete{}),
	0x10: t(ClientboundPlayDeclareCommands{}),
	0x11: t(ClientboundPlayTransaction{}),
	0x12: t(ClientboundPlayCloseWindow{}),
	0x13: t(ClientboundPlayWindowItems{}),
	0x14: t(ClientboundPlayCraftProgressBar{}),
	0x15: t(ClientboundPlaySetSlot{}),
	0x16: t(ClientboundPlaySetCooldown{}),
	0x17: t(ClientboundPluginMessagePacket{}),
	0x18: t(ClientboundPlayNamedSoundEffect{}),
	0x19: t(ClientboundPlayKickDisconnect{}),
	0x1A: t(ClientboundPlayEntityStatus{}),
	0x1B: t(ClientboundPlayExplosion{}),
	0x1C: t(ClientboundPlayUnloadChunk{}),
	0x1D: t(ClientboundPlayGameStateChange{}),
	0x1E: t(ClientboundPlayOpenHorseWindow{}),
	0x1F: t(ClientboundPlayKeepAlive{}),
	0x20: t(ClientboundPlayMapChunk{}),
	0x21: t(ClientboundPlayWorldEvent{}),
	0x22: t(ClientboundPlayWorldParticles{}),
	0x23: t(ClientboundPlayUpdateLight{}),
	0x24: t(ClientboundJoinGamePacket{}),
	0x25: t(ClientboundPlayMap{}),
	0x26: t(ClientboundPlayTradeList{}),
	0x27: t(ClientboundPlayRelEntityMove{}),
	0x28: t(ClientboundPlayEntityMoveLook{}),
	0x29: t(ClientboundPlayEntityLook{}),
	0x2A: t(ClientboundPlayEntity{}),
	0x2B: t(ClientboundPlayVehicleMove{}),
	0x2C: t(ClientboundPlayOpenBook{}),
	0x2D: t(ClientboundPlayOpenWindow{}),
	0x2E: t(ClientboundPlayOpenSignEntity{}),
	0x2F: t(ClientboundPlayCraftRecipeResponse{}),
	0x30: t(ClientboundPlayerAbilitiesPacket{}),
	0x31: t(ClientboundPlayCombatEvent{}),
	0x32: t(ClientboundPlayPlayerInfo{}),
	0x33: t(ClientboundPlayFacePlayer{}),
	0x34: t(ClientboundPlayPosition{}),
	0x35: t(ClientboundPlayUnlockRecipes{}),
	0x36: t(ClientboundPlayEntityDestroy{}),
	0x37: t(ClientboundPlayRemoveEntityEffect{}),
	0x38: t(ClientboundPlayResourcePackSend{}),
	0x39: t(ClientboundPlayRespawn{}),
	0x3A: t(ClientboundPlayEntityHeadRotation{}),
	0x3B: t(ClientboundPlayMultiBlockChange{}),
	0x3C: t(ClientboundPlaySelectAdvancementTab{}),
	0x3D: t(ClientboundPlayWorldBorder{}),
	0x3E: t(ClientboundPlayCamera{}),
	0x3F: t(ClientboundHeldItemChangePacket{}),
	0x40: t(ClientboundPlayUpdateViewPosition{}),
	0x41: t(ClientboundPlayUpdateViewDistance{}),
	0x42: t(ClientboundPlaySpawnPosition{}),
	0x43: t(ClientboundPlayScoreboardDisplayObjective{}),
	0x44: t(ClientboundPlayEntityMetadata{}),
	0x45: t(ClientboundPlayAttachEntity{}),
	0x46: t(ClientboundPlayEntityVelocity{}),
	0x47: t(ClientboundPlayEntityEquipment{}),
	0x48: t(ClientboundPlayExperience{}),
	0x49: t(ClientboundPlayUpdateHealth{}),
	0x4A: t(ClientboundPlayScoreboardObjective{}),
	0x4B: t(ClientboundPlaySetPassengers{}),
	0x4C: t(ClientboundPlayTeams{}),
	0x4D: t(ClientboundPlayScoreboardScore{}),
	0x4E: t(ClientboundPlayUpdateTime{}),
	0x4F: t(ClientboundPlayTitle{}),
	0x50: t(ClientboundPlayEntitySoundEffect{}),
	0x51: t(ClientboundPlaySoundEffect{}),
	0x52: t(ClientboundPlayStopSound{}),
	0x53: t(ClientboundPlayPlayerlistHeader{}),
	0x54: t(ClientboundPlayNbtQueryResponse{}),
	0x55: t(ClientboundPlayCollect{}),
	0x56: t(ClientboundPlayEntityTeleport{}),
	0x57: t(ClientboundPlayAdvancements{}),
	0x58: t(ClientboundPlayEntityUpdateAttributes{}),
	0x59: t(ClientboundPlayEntityEffect{}),
	0x5A: t(ClientboundDeclareRecipesPacket{}),
	0x5B: t(ClientboundPlayTags{}),
}

var PlayServerboundIds = map[int32]reflect.Type{
	0x00: t(ServerboundPlayTeleportConfirm{}),
	0x01: t(ServerboundPlayQueryBlockNbt{}),
	0x02: t(ServerboundPlaySetDifficulty{}),
	0x03: t(ServerboundPlayChat{}),
	0x04: t(ServerboundPlayClientCommand{}),
	0x05: t(ServerboundClientSettingsPacket{}),
	0x06: t(ServerboundPlayTabComplete{}),
	0x07: t(ServerboundPlayTransaction{}),
	0x08: t(ServerboundPlayEnchantItem{}),
	0x09: t(ServerboundPlayWindowClick{}),
	0x0A: t(ServerboundPlayCloseWindow{}),
	0x0B: t(ServerboundPluginMessagePacket{}),
	0x0C: t(ServerboundPlayEditBook{}),
	0x0D: t(ServerboundPlayQueryEntityNbt{}),
	0x0E: t(ServerboundInteractEntityPacket{}),
	0x0F: t(ServerboundPlayGenerateStructure{}),
	0x10: t(ServerboundPlayKeepAlive{}),
	0x11: t(ServerboundPlayLockDifficulty{}),
	0x12: t(ServerboundPlayPosition{}),
	0x13: t(ServerboundPlayPositionLook{}),
	0x14: t(ServerboundPlayLook{}),
	0x15: t(ServerboundPlayFlying{}),
	0x16: t(ServerboundPlayVehicleMove{}),
	0x17: t(ServerboundPlaySteerBoat{}),
	0x18: t(ServerboundPlayPickItem{}),
	0x19: t(ServerboundPlayCraftRecipeRequest{}),
	0x1A: t(ServerboundPlayAbilities{}),
	0x1B: t(ServerboundPlayBlockDig{}),
	0x1C: t(ServerboundPlayEntityAction{}),
	0x1D: t(ServerboundPlaySteerVehicle{}),
	0x1E: t(ServerboundPlayDisplayedRecipe{}),
	0x1F: t(ServerboundPlayRecipeBook{}),
	0x20: t(ServerboundPlayNameItem{}),
	0x21: t(ServerboundPlayResourcePackReceive{}),
	0x22: t(ServerboundAdvancementTabPacket{}),
	0x23: t(ServerboundPlaySelectTrade{}),
	0x24: t(ServerboundPlaySetBeaconEffect{}),
	0x25: t(ServerboundPlayHeldItemSlot{}),
	0x26: t(ServerboundPlayUpdateCommandBlock{}),
	0x27: t(ServerboundPlayUpdateCommandBlockMinecart{}),
	0x28: t(ServerboundPlaySetCreativeSlot{}),
	0x29: t(ServerboundPlayUpdateJigsawBlock{}),
	0x2A: t(ServerboundPlayUpdateStructureBlock{}),
	0x2B: t(ServerboundPlayUpdateSign{}),
	0x2C: t(ServerboundPlayArmAnimation{}),
	0x2D: t(ServerboundPlaySpectate{}),
	0x2E: t(ServerboundPlayBlockPlace{}),
	0x2F: t(ServerboundPlayUseItem{}),
}
