DebugMode = false
Difficulty = "normal"
Gamemode = "survival"
MOTD = "A JungleTree Server"
MaxOnlinePlayers = 20
Verbose = false

[JavaEdition]
  OnlineMode = true

[Network]
  IP = ""
  NetworkCompressionThreshold = 256
  Port = 25565
